[package]
name = "squidclient"
version = "0.1.1"
authors = ["Marise Hayashi <vyatheslav2707@mail.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
base64 = "0.12.3"
