[package]
name = "squidclient"
version = "0.1.0"
authors = ["Marise Hayashi <vyatheslav2707@mail.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.1"
base64 = "0.12.3"
